package catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// NewPostCatalogItemsParams creates a new PostCatalogItemsParams object
// with the default values initialized.
func NewPostCatalogItemsParams() *PostCatalogItemsParams {
	var ()
	return &PostCatalogItemsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostCatalogItemsParamsWithTimeout creates a new PostCatalogItemsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostCatalogItemsParamsWithTimeout(timeout time.Duration) *PostCatalogItemsParams {
	var ()
	return &PostCatalogItemsParams{

		timeout: timeout,
	}
}

// NewPostCatalogItemsParamsWithContext creates a new PostCatalogItemsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostCatalogItemsParamsWithContext(ctx context.Context) *PostCatalogItemsParams {
	var ()
	return &PostCatalogItemsParams{

		Context: ctx,
	}
}

/*PostCatalogItemsParams contains all the parameters to send to the API endpoint
for the post catalog items operation typically these are written to a http.Request
*/
type PostCatalogItemsParams struct {

	/*Request*/
	Request *models.Catalog

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the post catalog items params
func (o *PostCatalogItemsParams) WithTimeout(timeout time.Duration) *PostCatalogItemsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post catalog items params
func (o *PostCatalogItemsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post catalog items params
func (o *PostCatalogItemsParams) WithContext(ctx context.Context) *PostCatalogItemsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post catalog items params
func (o *PostCatalogItemsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithRequest adds the request to the post catalog items params
func (o *PostCatalogItemsParams) WithRequest(request *models.Catalog) *PostCatalogItemsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post catalog items params
func (o *PostCatalogItemsParams) SetRequest(request *models.Catalog) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostCatalogItemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Request == nil {
		o.Request = new(models.Catalog)
	}

	if err := r.SetBodyParam(o.Request); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
