package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetContainersUUIDVolumesVolumeUUIDParams creates a new GetContainersUUIDVolumesVolumeUUIDParams object
// with the default values initialized.
func NewGetContainersUUIDVolumesVolumeUUIDParams() *GetContainersUUIDVolumesVolumeUUIDParams {
	var ()
	return &GetContainersUUIDVolumesVolumeUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetContainersUUIDVolumesVolumeUUIDParamsWithTimeout creates a new GetContainersUUIDVolumesVolumeUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetContainersUUIDVolumesVolumeUUIDParamsWithTimeout(timeout time.Duration) *GetContainersUUIDVolumesVolumeUUIDParams {
	var ()
	return &GetContainersUUIDVolumesVolumeUUIDParams{

		timeout: timeout,
	}
}

// NewGetContainersUUIDVolumesVolumeUUIDParamsWithContext creates a new GetContainersUUIDVolumesVolumeUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetContainersUUIDVolumesVolumeUUIDParamsWithContext(ctx context.Context) *GetContainersUUIDVolumesVolumeUUIDParams {
	var ()
	return &GetContainersUUIDVolumesVolumeUUIDParams{

		Context: ctx,
	}
}

/*GetContainersUUIDVolumesVolumeUUIDParams contains all the parameters to send to the API endpoint
for the get containers UUID volumes volume UUID operation typically these are written to a http.Request
*/
type GetContainersUUIDVolumesVolumeUUIDParams struct {

	/*UUID
	  Uuid of the container

	*/
	UUID string
	/*VolumeUUID
	  Uuid of a volume

	*/
	VolumeUUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get containers UUID volumes volume UUID params
func (o *GetContainersUUIDVolumesVolumeUUIDParams) WithTimeout(timeout time.Duration) *GetContainersUUIDVolumesVolumeUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get containers UUID volumes volume UUID params
func (o *GetContainersUUIDVolumesVolumeUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get containers UUID volumes volume UUID params
func (o *GetContainersUUIDVolumesVolumeUUIDParams) WithContext(ctx context.Context) *GetContainersUUIDVolumesVolumeUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get containers UUID volumes volume UUID params
func (o *GetContainersUUIDVolumesVolumeUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithUUID adds the uuid to the get containers UUID volumes volume UUID params
func (o *GetContainersUUIDVolumesVolumeUUIDParams) WithUUID(uuid string) *GetContainersUUIDVolumesVolumeUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get containers UUID volumes volume UUID params
func (o *GetContainersUUIDVolumesVolumeUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WithVolumeUUID adds the volumeUUID to the get containers UUID volumes volume UUID params
func (o *GetContainersUUIDVolumesVolumeUUIDParams) WithVolumeUUID(volumeUUID string) *GetContainersUUIDVolumesVolumeUUIDParams {
	o.SetVolumeUUID(volumeUUID)
	return o
}

// SetVolumeUUID adds the volumeUuid to the get containers UUID volumes volume UUID params
func (o *GetContainersUUIDVolumesVolumeUUIDParams) SetVolumeUUID(volumeUUID string) {
	o.VolumeUUID = volumeUUID
}

// WriteToRequest writes these params to a swagger request
func (o *GetContainersUUIDVolumesVolumeUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	// path param volume_uuid
	if err := r.SetPathParam("volume_uuid", o.VolumeUUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
