package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// PostContainersReader is a Reader for the PostContainers structure.
type PostContainersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostContainersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostContainersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostContainersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostContainersOK creates a PostContainersOK with default headers values
func NewPostContainersOK() *PostContainersOK {
	return &PostContainersOK{}
}

/*PostContainersOK handles this case with default header values.

Success
*/
type PostContainersOK struct {
	Payload *models.ContainerIntentResponse
}

func (o *PostContainersOK) Error() string {
	return fmt.Sprintf("[POST /containers][%d] postContainersOK  %+v", 200, o.Payload)
}

func (o *PostContainersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerIntentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostContainersDefault creates a PostContainersDefault with default headers values
func NewPostContainersDefault(code int) *PostContainersDefault {
	return &PostContainersDefault{
		_statusCode: code,
	}
}

/*PostContainersDefault handles this case with default header values.

Server Error
*/
type PostContainersDefault struct {
	_statusCode int

	Payload *models.ContainerStatus
}

// Code gets the status code for the post containers default response
func (o *PostContainersDefault) Code() int {
	return o._statusCode
}

func (o *PostContainersDefault) Error() string {
	return fmt.Sprintf("[POST /containers][%d] PostContainers default  %+v", o._statusCode, o.Payload)
}

func (o *PostContainersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
