package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// DeleteRolesUUIDReader is a Reader for the DeleteRolesUUID structure.
type DeleteRolesUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRolesUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteRolesUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteRolesUUIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteRolesUUIDOK creates a DeleteRolesUUIDOK with default headers values
func NewDeleteRolesUUIDOK() *DeleteRolesUUIDOK {
	return &DeleteRolesUUIDOK{}
}

/*DeleteRolesUUIDOK handles this case with default header values.

Successful operation
*/
type DeleteRolesUUIDOK struct {
}

func (o *DeleteRolesUUIDOK) Error() string {
	return fmt.Sprintf("[DELETE /roles/{uuid}][%d] deleteRolesUuidOK ", 200)
}

func (o *DeleteRolesUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRolesUUIDDefault creates a DeleteRolesUUIDDefault with default headers values
func NewDeleteRolesUUIDDefault(code int) *DeleteRolesUUIDDefault {
	return &DeleteRolesUUIDDefault{
		_statusCode: code,
	}
}

/*DeleteRolesUUIDDefault handles this case with default header values.

Error
*/
type DeleteRolesUUIDDefault struct {
	_statusCode int

	Payload *models.RoleStatus
}

// Code gets the status code for the delete roles UUID default response
func (o *DeleteRolesUUIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteRolesUUIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /roles/{uuid}][%d] DeleteRolesUUID default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteRolesUUIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
