package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// PostRolesReader is a Reader for the PostRoles structure.
type PostRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostRolesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostRolesOK creates a PostRolesOK with default headers values
func NewPostRolesOK() *PostRolesOK {
	return &PostRolesOK{}
}

/*PostRolesOK handles this case with default header values.

Successful operation
*/
type PostRolesOK struct {
	Payload *models.Role
}

func (o *PostRolesOK) Error() string {
	return fmt.Sprintf("[POST /roles][%d] postRolesOK  %+v", 200, o.Payload)
}

func (o *PostRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Role)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRolesDefault creates a PostRolesDefault with default headers values
func NewPostRolesDefault(code int) *PostRolesDefault {
	return &PostRolesDefault{
		_statusCode: code,
	}
}

/*PostRolesDefault handles this case with default header values.

Error
*/
type PostRolesDefault struct {
	_statusCode int

	Payload *models.RoleStatus
}

// Code gets the status code for the post roles default response
func (o *PostRolesDefault) Code() int {
	return o._statusCode
}

func (o *PostRolesDefault) Error() string {
	return fmt.Sprintf("[POST /roles][%d] PostRoles default  %+v", o._statusCode, o.Payload)
}

func (o *PostRolesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
