package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// PostRolesListReader is a Reader for the PostRolesList structure.
type PostRolesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRolesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRolesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostRolesListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostRolesListOK creates a PostRolesListOK with default headers values
func NewPostRolesListOK() *PostRolesListOK {
	return &PostRolesListOK{}
}

/*PostRolesListOK handles this case with default header values.

Successful operation
*/
type PostRolesListOK struct {
	Payload *models.RoleList
}

func (o *PostRolesListOK) Error() string {
	return fmt.Sprintf("[POST /roles/list][%d] postRolesListOK  %+v", 200, o.Payload)
}

func (o *PostRolesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRolesListDefault creates a PostRolesListDefault with default headers values
func NewPostRolesListDefault(code int) *PostRolesListDefault {
	return &PostRolesListDefault{
		_statusCode: code,
	}
}

/*PostRolesListDefault handles this case with default header values.

Error
*/
type PostRolesListDefault struct {
	_statusCode int

	Payload *models.RoleStatus
}

// Code gets the status code for the post roles list default response
func (o *PostRolesListDefault) Code() int {
	return o._statusCode
}

func (o *PostRolesListDefault) Error() string {
	return fmt.Sprintf("[POST /roles/list][%d] PostRolesList default  %+v", o._statusCode, o.Payload)
}

func (o *PostRolesListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
