package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// PutRolesUUIDReader is a Reader for the PutRolesUUID structure.
type PutRolesUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutRolesUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutRolesUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPutRolesUUIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPutRolesUUIDOK creates a PutRolesUUIDOK with default headers values
func NewPutRolesUUIDOK() *PutRolesUUIDOK {
	return &PutRolesUUIDOK{}
}

/*PutRolesUUIDOK handles this case with default header values.

Successful operation
*/
type PutRolesUUIDOK struct {
	Payload *models.Role
}

func (o *PutRolesUUIDOK) Error() string {
	return fmt.Sprintf("[PUT /roles/{uuid}][%d] putRolesUuidOK  %+v", 200, o.Payload)
}

func (o *PutRolesUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Role)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutRolesUUIDDefault creates a PutRolesUUIDDefault with default headers values
func NewPutRolesUUIDDefault(code int) *PutRolesUUIDDefault {
	return &PutRolesUUIDDefault{
		_statusCode: code,
	}
}

/*PutRolesUUIDDefault handles this case with default header values.

Error
*/
type PutRolesUUIDDefault struct {
	_statusCode int

	Payload *models.RoleStatus
}

// Code gets the status code for the put roles UUID default response
func (o *PutRolesUUIDDefault) Code() int {
	return o._statusCode
}

func (o *PutRolesUUIDDefault) Error() string {
	return fmt.Sprintf("[PUT /roles/{uuid}][%d] PutRolesUUID default  %+v", o._statusCode, o.Payload)
}

func (o *PutRolesUUIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
