package volume_group_snapshot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteVolumeGroupSnapshotsUUIDParams creates a new DeleteVolumeGroupSnapshotsUUIDParams object
// with the default values initialized.
func NewDeleteVolumeGroupSnapshotsUUIDParams() *DeleteVolumeGroupSnapshotsUUIDParams {
	var ()
	return &DeleteVolumeGroupSnapshotsUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVolumeGroupSnapshotsUUIDParamsWithTimeout creates a new DeleteVolumeGroupSnapshotsUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteVolumeGroupSnapshotsUUIDParamsWithTimeout(timeout time.Duration) *DeleteVolumeGroupSnapshotsUUIDParams {
	var ()
	return &DeleteVolumeGroupSnapshotsUUIDParams{

		timeout: timeout,
	}
}

// NewDeleteVolumeGroupSnapshotsUUIDParamsWithContext creates a new DeleteVolumeGroupSnapshotsUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteVolumeGroupSnapshotsUUIDParamsWithContext(ctx context.Context) *DeleteVolumeGroupSnapshotsUUIDParams {
	var ()
	return &DeleteVolumeGroupSnapshotsUUIDParams{

		Context: ctx,
	}
}

/*DeleteVolumeGroupSnapshotsUUIDParams contains all the parameters to send to the API endpoint
for the delete volume group snapshots UUID operation typically these are written to a http.Request
*/
type DeleteVolumeGroupSnapshotsUUIDParams struct {

	/*UUID*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the delete volume group snapshots UUID params
func (o *DeleteVolumeGroupSnapshotsUUIDParams) WithTimeout(timeout time.Duration) *DeleteVolumeGroupSnapshotsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete volume group snapshots UUID params
func (o *DeleteVolumeGroupSnapshotsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete volume group snapshots UUID params
func (o *DeleteVolumeGroupSnapshotsUUIDParams) WithContext(ctx context.Context) *DeleteVolumeGroupSnapshotsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete volume group snapshots UUID params
func (o *DeleteVolumeGroupSnapshotsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithUUID adds the uuid to the delete volume group snapshots UUID params
func (o *DeleteVolumeGroupSnapshotsUUIDParams) WithUUID(uuid string) *DeleteVolumeGroupSnapshotsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete volume group snapshots UUID params
func (o *DeleteVolumeGroupSnapshotsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVolumeGroupSnapshotsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
