package volume_group_snapshot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// NewPostVolumeGroupSnapshotsParams creates a new PostVolumeGroupSnapshotsParams object
// with the default values initialized.
func NewPostVolumeGroupSnapshotsParams() *PostVolumeGroupSnapshotsParams {
	var ()
	return &PostVolumeGroupSnapshotsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostVolumeGroupSnapshotsParamsWithTimeout creates a new PostVolumeGroupSnapshotsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostVolumeGroupSnapshotsParamsWithTimeout(timeout time.Duration) *PostVolumeGroupSnapshotsParams {
	var ()
	return &PostVolumeGroupSnapshotsParams{

		timeout: timeout,
	}
}

// NewPostVolumeGroupSnapshotsParamsWithContext creates a new PostVolumeGroupSnapshotsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostVolumeGroupSnapshotsParamsWithContext(ctx context.Context) *PostVolumeGroupSnapshotsParams {
	var ()
	return &PostVolumeGroupSnapshotsParams{

		Context: ctx,
	}
}

/*PostVolumeGroupSnapshotsParams contains all the parameters to send to the API endpoint
for the post volume group snapshots operation typically these are written to a http.Request
*/
type PostVolumeGroupSnapshotsParams struct {

	/*Body*/
	Body *models.VolumeGroupSnapshotIntentInput

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the post volume group snapshots params
func (o *PostVolumeGroupSnapshotsParams) WithTimeout(timeout time.Duration) *PostVolumeGroupSnapshotsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post volume group snapshots params
func (o *PostVolumeGroupSnapshotsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post volume group snapshots params
func (o *PostVolumeGroupSnapshotsParams) WithContext(ctx context.Context) *PostVolumeGroupSnapshotsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post volume group snapshots params
func (o *PostVolumeGroupSnapshotsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the post volume group snapshots params
func (o *PostVolumeGroupSnapshotsParams) WithBody(body *models.VolumeGroupSnapshotIntentInput) *PostVolumeGroupSnapshotsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post volume group snapshots params
func (o *PostVolumeGroupSnapshotsParams) SetBody(body *models.VolumeGroupSnapshotIntentInput) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostVolumeGroupSnapshotsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.VolumeGroupSnapshotIntentInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
