package volume_group_snapshot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// PostVolumeGroupSnapshotsReader is a Reader for the PostVolumeGroupSnapshots structure.
type PostVolumeGroupSnapshotsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostVolumeGroupSnapshotsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostVolumeGroupSnapshotsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostVolumeGroupSnapshotsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostVolumeGroupSnapshotsOK creates a PostVolumeGroupSnapshotsOK with default headers values
func NewPostVolumeGroupSnapshotsOK() *PostVolumeGroupSnapshotsOK {
	return &PostVolumeGroupSnapshotsOK{}
}

/*PostVolumeGroupSnapshotsOK handles this case with default header values.

Request Succeeded
*/
type PostVolumeGroupSnapshotsOK struct {
	Payload *models.VolumeGroupSnapshotIntentResponse
}

func (o *PostVolumeGroupSnapshotsOK) Error() string {
	return fmt.Sprintf("[POST /volume_group_snapshots][%d] postVolumeGroupSnapshotsOK  %+v", 200, o.Payload)
}

func (o *PostVolumeGroupSnapshotsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VolumeGroupSnapshotIntentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostVolumeGroupSnapshotsDefault creates a PostVolumeGroupSnapshotsDefault with default headers values
func NewPostVolumeGroupSnapshotsDefault(code int) *PostVolumeGroupSnapshotsDefault {
	return &PostVolumeGroupSnapshotsDefault{
		_statusCode: code,
	}
}

/*PostVolumeGroupSnapshotsDefault handles this case with default header values.

Internal Error
*/
type PostVolumeGroupSnapshotsDefault struct {
	_statusCode int

	Payload *models.VolumeGroupSnapshotStatus
}

// Code gets the status code for the post volume group snapshots default response
func (o *PostVolumeGroupSnapshotsDefault) Code() int {
	return o._statusCode
}

func (o *PostVolumeGroupSnapshotsDefault) Error() string {
	return fmt.Sprintf("[POST /volume_group_snapshots][%d] PostVolumeGroupSnapshots default  %+v", o._statusCode, o.Payload)
}

func (o *PostVolumeGroupSnapshotsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VolumeGroupSnapshotStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
