package workflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// NewPostWorkflowsParams creates a new PostWorkflowsParams object
// with the default values initialized.
func NewPostWorkflowsParams() *PostWorkflowsParams {
	var ()
	return &PostWorkflowsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostWorkflowsParamsWithTimeout creates a new PostWorkflowsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostWorkflowsParamsWithTimeout(timeout time.Duration) *PostWorkflowsParams {
	var ()
	return &PostWorkflowsParams{

		timeout: timeout,
	}
}

// NewPostWorkflowsParamsWithContext creates a new PostWorkflowsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostWorkflowsParamsWithContext(ctx context.Context) *PostWorkflowsParams {
	var ()
	return &PostWorkflowsParams{

		Context: ctx,
	}
}

/*PostWorkflowsParams contains all the parameters to send to the API endpoint
for the post workflows operation typically these are written to a http.Request
*/
type PostWorkflowsParams struct {

	/*Body
	  Request body

	*/
	Body *models.WorkflowIntentInput

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the post workflows params
func (o *PostWorkflowsParams) WithTimeout(timeout time.Duration) *PostWorkflowsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post workflows params
func (o *PostWorkflowsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post workflows params
func (o *PostWorkflowsParams) WithContext(ctx context.Context) *PostWorkflowsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post workflows params
func (o *PostWorkflowsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the post workflows params
func (o *PostWorkflowsParams) WithBody(body *models.WorkflowIntentInput) *PostWorkflowsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post workflows params
func (o *PostWorkflowsParams) SetBody(body *models.WorkflowIntentInput) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostWorkflowsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.WorkflowIntentInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
