package workflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// NewPutWorkflowsUUIDParams creates a new PutWorkflowsUUIDParams object
// with the default values initialized.
func NewPutWorkflowsUUIDParams() *PutWorkflowsUUIDParams {
	var ()
	return &PutWorkflowsUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutWorkflowsUUIDParamsWithTimeout creates a new PutWorkflowsUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutWorkflowsUUIDParamsWithTimeout(timeout time.Duration) *PutWorkflowsUUIDParams {
	var ()
	return &PutWorkflowsUUIDParams{

		timeout: timeout,
	}
}

// NewPutWorkflowsUUIDParamsWithContext creates a new PutWorkflowsUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutWorkflowsUUIDParamsWithContext(ctx context.Context) *PutWorkflowsUUIDParams {
	var ()
	return &PutWorkflowsUUIDParams{

		Context: ctx,
	}
}

/*PutWorkflowsUUIDParams contains all the parameters to send to the API endpoint
for the put workflows UUID operation typically these are written to a http.Request
*/
type PutWorkflowsUUIDParams struct {

	/*Body*/
	Body *models.WorkflowIntentInput
	/*UUID
	  Uuid of workflow to be updated

	*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the put workflows UUID params
func (o *PutWorkflowsUUIDParams) WithTimeout(timeout time.Duration) *PutWorkflowsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put workflows UUID params
func (o *PutWorkflowsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put workflows UUID params
func (o *PutWorkflowsUUIDParams) WithContext(ctx context.Context) *PutWorkflowsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put workflows UUID params
func (o *PutWorkflowsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the put workflows UUID params
func (o *PutWorkflowsUUIDParams) WithBody(body *models.WorkflowIntentInput) *PutWorkflowsUUIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put workflows UUID params
func (o *PutWorkflowsUUIDParams) SetBody(body *models.WorkflowIntentInput) {
	o.Body = body
}

// WithUUID adds the uuid to the put workflows UUID params
func (o *PutWorkflowsUUIDParams) WithUUID(uuid string) *PutWorkflowsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the put workflows UUID params
func (o *PutWorkflowsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *PutWorkflowsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.WorkflowIntentInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
