package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteClustersUUIDCertificatesClientAuthReader is a Reader for the DeleteClustersUUIDCertificatesClientAuth structure.
type DeleteClustersUUIDCertificatesClientAuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteClustersUUIDCertificatesClientAuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteClustersUUIDCertificatesClientAuthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteClustersUUIDCertificatesClientAuthDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteClustersUUIDCertificatesClientAuthOK creates a DeleteClustersUUIDCertificatesClientAuthOK with default headers values
func NewDeleteClustersUUIDCertificatesClientAuthOK() *DeleteClustersUUIDCertificatesClientAuthOK {
	return &DeleteClustersUUIDCertificatesClientAuthOK{}
}

/*DeleteClustersUUIDCertificatesClientAuthOK handles this case with default header values.

Request Succeeded
*/
type DeleteClustersUUIDCertificatesClientAuthOK struct {
}

func (o *DeleteClustersUUIDCertificatesClientAuthOK) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{uuid}/certificates/client_auth][%d] deleteClustersUuidCertificatesClientAuthOK ", 200)
}

func (o *DeleteClustersUUIDCertificatesClientAuthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteClustersUUIDCertificatesClientAuthDefault creates a DeleteClustersUUIDCertificatesClientAuthDefault with default headers values
func NewDeleteClustersUUIDCertificatesClientAuthDefault(code int) *DeleteClustersUUIDCertificatesClientAuthDefault {
	return &DeleteClustersUUIDCertificatesClientAuthDefault{
		_statusCode: code,
	}
}

/*DeleteClustersUUIDCertificatesClientAuthDefault handles this case with default header values.

Internal Error
*/
type DeleteClustersUUIDCertificatesClientAuthDefault struct {
	_statusCode int
}

// Code gets the status code for the delete clusters UUID certificates client auth default response
func (o *DeleteClustersUUIDCertificatesClientAuthDefault) Code() int {
	return o._statusCode
}

func (o *DeleteClustersUUIDCertificatesClientAuthDefault) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{uuid}/certificates/client_auth][%d] DeleteClustersUUIDCertificatesClientAuth default ", o._statusCode)
}

func (o *DeleteClustersUUIDCertificatesClientAuthDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
