package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams creates a new GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams object
// with the default values initialized.
func NewGetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams() *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams {
	var ()
	return &GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetClustersUUIDDirectoryServicesDirectoryServiceUUIDParamsWithTimeout creates a new GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetClustersUUIDDirectoryServicesDirectoryServiceUUIDParamsWithTimeout(timeout time.Duration) *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams {
	var ()
	return &GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams{

		timeout: timeout,
	}
}

// NewGetClustersUUIDDirectoryServicesDirectoryServiceUUIDParamsWithContext creates a new GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetClustersUUIDDirectoryServicesDirectoryServiceUUIDParamsWithContext(ctx context.Context) *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams {
	var ()
	return &GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams{

		Context: ctx,
	}
}

/*GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams contains all the parameters to send to the API endpoint
for the get clusters UUID directory services directory service UUID operation typically these are written to a http.Request
*/
type GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams struct {

	/*DirectoryServiceUUID*/
	DirectoryServiceUUID string
	/*UUID
	  The UUID of the entity.

	*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get clusters UUID directory services directory service UUID params
func (o *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams) WithTimeout(timeout time.Duration) *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get clusters UUID directory services directory service UUID params
func (o *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get clusters UUID directory services directory service UUID params
func (o *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams) WithContext(ctx context.Context) *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get clusters UUID directory services directory service UUID params
func (o *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithDirectoryServiceUUID adds the directoryServiceUUID to the get clusters UUID directory services directory service UUID params
func (o *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams) WithDirectoryServiceUUID(directoryServiceUUID string) *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams {
	o.SetDirectoryServiceUUID(directoryServiceUUID)
	return o
}

// SetDirectoryServiceUUID adds the directoryServiceUuid to the get clusters UUID directory services directory service UUID params
func (o *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams) SetDirectoryServiceUUID(directoryServiceUUID string) {
	o.DirectoryServiceUUID = directoryServiceUUID
}

// WithUUID adds the uuid to the get clusters UUID directory services directory service UUID params
func (o *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams) WithUUID(uuid string) *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get clusters UUID directory services directory service UUID params
func (o *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetClustersUUIDDirectoryServicesDirectoryServiceUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param directory_service_uuid
	if err := r.SetPathParam("directory_service_uuid", o.DirectoryServiceUUID); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
