package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// PostClustersUUIDCloudCredentialsCloudTypeListReader is a Reader for the PostClustersUUIDCloudCredentialsCloudTypeList structure.
type PostClustersUUIDCloudCredentialsCloudTypeListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostClustersUUIDCloudCredentialsCloudTypeListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostClustersUUIDCloudCredentialsCloudTypeListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostClustersUUIDCloudCredentialsCloudTypeListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostClustersUUIDCloudCredentialsCloudTypeListOK creates a PostClustersUUIDCloudCredentialsCloudTypeListOK with default headers values
func NewPostClustersUUIDCloudCredentialsCloudTypeListOK() *PostClustersUUIDCloudCredentialsCloudTypeListOK {
	return &PostClustersUUIDCloudCredentialsCloudTypeListOK{}
}

/*PostClustersUUIDCloudCredentialsCloudTypeListOK handles this case with default header values.

Request Succeeded
*/
type PostClustersUUIDCloudCredentialsCloudTypeListOK struct {
	Payload *models.CloudCredentialsListIntentResponse
}

func (o *PostClustersUUIDCloudCredentialsCloudTypeListOK) Error() string {
	return fmt.Sprintf("[POST /clusters/{uuid}/cloud_credentials/{cloud_type}/list][%d] postClustersUuidCloudCredentialsCloudTypeListOK  %+v", 200, o.Payload)
}

func (o *PostClustersUUIDCloudCredentialsCloudTypeListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudCredentialsListIntentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostClustersUUIDCloudCredentialsCloudTypeListDefault creates a PostClustersUUIDCloudCredentialsCloudTypeListDefault with default headers values
func NewPostClustersUUIDCloudCredentialsCloudTypeListDefault(code int) *PostClustersUUIDCloudCredentialsCloudTypeListDefault {
	return &PostClustersUUIDCloudCredentialsCloudTypeListDefault{
		_statusCode: code,
	}
}

/*PostClustersUUIDCloudCredentialsCloudTypeListDefault handles this case with default header values.

Internal Error
*/
type PostClustersUUIDCloudCredentialsCloudTypeListDefault struct {
	_statusCode int

	Payload *models.CloudCredentialsStatus
}

// Code gets the status code for the post clusters UUID cloud credentials cloud type list default response
func (o *PostClustersUUIDCloudCredentialsCloudTypeListDefault) Code() int {
	return o._statusCode
}

func (o *PostClustersUUIDCloudCredentialsCloudTypeListDefault) Error() string {
	return fmt.Sprintf("[POST /clusters/{uuid}/cloud_credentials/{cloud_type}/list][%d] PostClustersUUIDCloudCredentialsCloudTypeList default  %+v", o._statusCode, o.Payload)
}

func (o *PostClustersUUIDCloudCredentialsCloudTypeListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudCredentialsStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
