package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// NewPostClustersUUIDCloudCredentialsCloudTypeParams creates a new PostClustersUUIDCloudCredentialsCloudTypeParams object
// with the default values initialized.
func NewPostClustersUUIDCloudCredentialsCloudTypeParams() *PostClustersUUIDCloudCredentialsCloudTypeParams {
	var ()
	return &PostClustersUUIDCloudCredentialsCloudTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostClustersUUIDCloudCredentialsCloudTypeParamsWithTimeout creates a new PostClustersUUIDCloudCredentialsCloudTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostClustersUUIDCloudCredentialsCloudTypeParamsWithTimeout(timeout time.Duration) *PostClustersUUIDCloudCredentialsCloudTypeParams {
	var ()
	return &PostClustersUUIDCloudCredentialsCloudTypeParams{

		timeout: timeout,
	}
}

// NewPostClustersUUIDCloudCredentialsCloudTypeParamsWithContext creates a new PostClustersUUIDCloudCredentialsCloudTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostClustersUUIDCloudCredentialsCloudTypeParamsWithContext(ctx context.Context) *PostClustersUUIDCloudCredentialsCloudTypeParams {
	var ()
	return &PostClustersUUIDCloudCredentialsCloudTypeParams{

		Context: ctx,
	}
}

/*PostClustersUUIDCloudCredentialsCloudTypeParams contains all the parameters to send to the API endpoint
for the post clusters UUID cloud credentials cloud type operation typically these are written to a http.Request
*/
type PostClustersUUIDCloudCredentialsCloudTypeParams struct {

	/*CloudType*/
	CloudType string
	/*Spec*/
	Spec *models.CloudCredentialsIntentInput
	/*UUID*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the post clusters UUID cloud credentials cloud type params
func (o *PostClustersUUIDCloudCredentialsCloudTypeParams) WithTimeout(timeout time.Duration) *PostClustersUUIDCloudCredentialsCloudTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post clusters UUID cloud credentials cloud type params
func (o *PostClustersUUIDCloudCredentialsCloudTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post clusters UUID cloud credentials cloud type params
func (o *PostClustersUUIDCloudCredentialsCloudTypeParams) WithContext(ctx context.Context) *PostClustersUUIDCloudCredentialsCloudTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post clusters UUID cloud credentials cloud type params
func (o *PostClustersUUIDCloudCredentialsCloudTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithCloudType adds the cloudType to the post clusters UUID cloud credentials cloud type params
func (o *PostClustersUUIDCloudCredentialsCloudTypeParams) WithCloudType(cloudType string) *PostClustersUUIDCloudCredentialsCloudTypeParams {
	o.SetCloudType(cloudType)
	return o
}

// SetCloudType adds the cloudType to the post clusters UUID cloud credentials cloud type params
func (o *PostClustersUUIDCloudCredentialsCloudTypeParams) SetCloudType(cloudType string) {
	o.CloudType = cloudType
}

// WithSpec adds the spec to the post clusters UUID cloud credentials cloud type params
func (o *PostClustersUUIDCloudCredentialsCloudTypeParams) WithSpec(spec *models.CloudCredentialsIntentInput) *PostClustersUUIDCloudCredentialsCloudTypeParams {
	o.SetSpec(spec)
	return o
}

// SetSpec adds the spec to the post clusters UUID cloud credentials cloud type params
func (o *PostClustersUUIDCloudCredentialsCloudTypeParams) SetSpec(spec *models.CloudCredentialsIntentInput) {
	o.Spec = spec
}

// WithUUID adds the uuid to the post clusters UUID cloud credentials cloud type params
func (o *PostClustersUUIDCloudCredentialsCloudTypeParams) WithUUID(uuid string) *PostClustersUUIDCloudCredentialsCloudTypeParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the post clusters UUID cloud credentials cloud type params
func (o *PostClustersUUIDCloudCredentialsCloudTypeParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *PostClustersUUIDCloudCredentialsCloudTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param cloud_type
	if err := r.SetPathParam("cloud_type", o.CloudType); err != nil {
		return err
	}

	if o.Spec == nil {
		o.Spec = new(models.CloudCredentialsIntentInput)
	}

	if err := r.SetBodyParam(o.Spec); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
