package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// NewPutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams creates a new PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams object
// with the default values initialized.
func NewPutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams() *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams {
	var ()
	return &PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParamsWithTimeout creates a new PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParamsWithTimeout(timeout time.Duration) *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams {
	var ()
	return &PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams{

		timeout: timeout,
	}
}

// NewPutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParamsWithContext creates a new PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParamsWithContext(ctx context.Context) *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams {
	var ()
	return &PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams{

		Context: ctx,
	}
}

/*PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams contains all the parameters to send to the API endpoint
for the put clusters UUID cloud credentials cloud type cloud credentials UUID operation typically these are written to a http.Request
*/
type PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams struct {

	/*CloudCredentialsUUID*/
	CloudCredentialsUUID int64
	/*CloudType*/
	CloudType string
	/*Spec*/
	Spec *models.CloudCredentialsIntentInput
	/*UUID*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the put clusters UUID cloud credentials cloud type cloud credentials UUID params
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) WithTimeout(timeout time.Duration) *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put clusters UUID cloud credentials cloud type cloud credentials UUID params
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put clusters UUID cloud credentials cloud type cloud credentials UUID params
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) WithContext(ctx context.Context) *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put clusters UUID cloud credentials cloud type cloud credentials UUID params
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithCloudCredentialsUUID adds the cloudCredentialsUUID to the put clusters UUID cloud credentials cloud type cloud credentials UUID params
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) WithCloudCredentialsUUID(cloudCredentialsUUID int64) *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams {
	o.SetCloudCredentialsUUID(cloudCredentialsUUID)
	return o
}

// SetCloudCredentialsUUID adds the cloudCredentialsUuid to the put clusters UUID cloud credentials cloud type cloud credentials UUID params
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) SetCloudCredentialsUUID(cloudCredentialsUUID int64) {
	o.CloudCredentialsUUID = cloudCredentialsUUID
}

// WithCloudType adds the cloudType to the put clusters UUID cloud credentials cloud type cloud credentials UUID params
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) WithCloudType(cloudType string) *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams {
	o.SetCloudType(cloudType)
	return o
}

// SetCloudType adds the cloudType to the put clusters UUID cloud credentials cloud type cloud credentials UUID params
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) SetCloudType(cloudType string) {
	o.CloudType = cloudType
}

// WithSpec adds the spec to the put clusters UUID cloud credentials cloud type cloud credentials UUID params
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) WithSpec(spec *models.CloudCredentialsIntentInput) *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams {
	o.SetSpec(spec)
	return o
}

// SetSpec adds the spec to the put clusters UUID cloud credentials cloud type cloud credentials UUID params
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) SetSpec(spec *models.CloudCredentialsIntentInput) {
	o.Spec = spec
}

// WithUUID adds the uuid to the put clusters UUID cloud credentials cloud type cloud credentials UUID params
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) WithUUID(uuid string) *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the put clusters UUID cloud credentials cloud type cloud credentials UUID params
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *PutClustersUUIDCloudCredentialsCloudTypeCloudCredentialsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param cloud_credentials_uuid
	if err := r.SetPathParam("cloud_credentials_uuid", swag.FormatInt64(o.CloudCredentialsUUID)); err != nil {
		return err
	}

	// path param cloud_type
	if err := r.SetPathParam("cloud_type", o.CloudType); err != nil {
		return err
	}

	if o.Spec == nil {
		o.Spec = new(models.CloudCredentialsIntentInput)
	}

	if err := r.SetBodyParam(o.Spec); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
