package packet_processor_chain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// PostPacketProcessorChainsListReader is a Reader for the PostPacketProcessorChainsList structure.
type PostPacketProcessorChainsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostPacketProcessorChainsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostPacketProcessorChainsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostPacketProcessorChainsListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostPacketProcessorChainsListOK creates a PostPacketProcessorChainsListOK with default headers values
func NewPostPacketProcessorChainsListOK() *PostPacketProcessorChainsListOK {
	return &PostPacketProcessorChainsListOK{}
}

/*PostPacketProcessorChainsListOK handles this case with default header values.

Successful operation
*/
type PostPacketProcessorChainsListOK struct {
	Payload *models.PacketProcessorChainListIntentResponse
}

func (o *PostPacketProcessorChainsListOK) Error() string {
	return fmt.Sprintf("[POST /packet_processor_chains/list][%d] postPacketProcessorChainsListOK  %+v", 200, o.Payload)
}

func (o *PostPacketProcessorChainsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PacketProcessorChainListIntentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostPacketProcessorChainsListDefault creates a PostPacketProcessorChainsListDefault with default headers values
func NewPostPacketProcessorChainsListDefault(code int) *PostPacketProcessorChainsListDefault {
	return &PostPacketProcessorChainsListDefault{
		_statusCode: code,
	}
}

/*PostPacketProcessorChainsListDefault handles this case with default header values.

Error
*/
type PostPacketProcessorChainsListDefault struct {
	_statusCode int

	Payload *models.PacketProcessorChainStatus
}

// Code gets the status code for the post packet processor chains list default response
func (o *PostPacketProcessorChainsListDefault) Code() int {
	return o._statusCode
}

func (o *PostPacketProcessorChainsListDefault) Error() string {
	return fmt.Sprintf("[POST /packet_processor_chains/list][%d] PostPacketProcessorChainsList default  %+v", o._statusCode, o.Payload)
}

func (o *PostPacketProcessorChainsListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PacketProcessorChainStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
