package availability_zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAvailabilityZonesUUIDParams creates a new DeleteAvailabilityZonesUUIDParams object
// with the default values initialized.
func NewDeleteAvailabilityZonesUUIDParams() *DeleteAvailabilityZonesUUIDParams {
	var ()
	return &DeleteAvailabilityZonesUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAvailabilityZonesUUIDParamsWithTimeout creates a new DeleteAvailabilityZonesUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAvailabilityZonesUUIDParamsWithTimeout(timeout time.Duration) *DeleteAvailabilityZonesUUIDParams {
	var ()
	return &DeleteAvailabilityZonesUUIDParams{

		timeout: timeout,
	}
}

// NewDeleteAvailabilityZonesUUIDParamsWithContext creates a new DeleteAvailabilityZonesUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAvailabilityZonesUUIDParamsWithContext(ctx context.Context) *DeleteAvailabilityZonesUUIDParams {
	var ()
	return &DeleteAvailabilityZonesUUIDParams{

		Context: ctx,
	}
}

/*DeleteAvailabilityZonesUUIDParams contains all the parameters to send to the API endpoint
for the delete availability zones UUID operation typically these are written to a http.Request
*/
type DeleteAvailabilityZonesUUIDParams struct {

	/*UUID
	  The UUID of the entity.

	*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the delete availability zones UUID params
func (o *DeleteAvailabilityZonesUUIDParams) WithTimeout(timeout time.Duration) *DeleteAvailabilityZonesUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete availability zones UUID params
func (o *DeleteAvailabilityZonesUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete availability zones UUID params
func (o *DeleteAvailabilityZonesUUIDParams) WithContext(ctx context.Context) *DeleteAvailabilityZonesUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete availability zones UUID params
func (o *DeleteAvailabilityZonesUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithUUID adds the uuid to the delete availability zones UUID params
func (o *DeleteAvailabilityZonesUUIDParams) WithUUID(uuid string) *DeleteAvailabilityZonesUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete availability zones UUID params
func (o *DeleteAvailabilityZonesUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAvailabilityZonesUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
