package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNetworksUUIDParams creates a new GetNetworksUUIDParams object
// with the default values initialized.
func NewGetNetworksUUIDParams() *GetNetworksUUIDParams {
	var ()
	return &GetNetworksUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworksUUIDParamsWithTimeout creates a new GetNetworksUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNetworksUUIDParamsWithTimeout(timeout time.Duration) *GetNetworksUUIDParams {
	var ()
	return &GetNetworksUUIDParams{

		timeout: timeout,
	}
}

// NewGetNetworksUUIDParamsWithContext creates a new GetNetworksUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNetworksUUIDParamsWithContext(ctx context.Context) *GetNetworksUUIDParams {
	var ()
	return &GetNetworksUUIDParams{

		Context: ctx,
	}
}

/*GetNetworksUUIDParams contains all the parameters to send to the API endpoint
for the get networks UUID operation typically these are written to a http.Request
*/
type GetNetworksUUIDParams struct {

	/*UUID
	  The UUID of the entity.

	*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get networks UUID params
func (o *GetNetworksUUIDParams) WithTimeout(timeout time.Duration) *GetNetworksUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get networks UUID params
func (o *GetNetworksUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get networks UUID params
func (o *GetNetworksUUIDParams) WithContext(ctx context.Context) *GetNetworksUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get networks UUID params
func (o *GetNetworksUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithUUID adds the uuid to the get networks UUID params
func (o *GetNetworksUUIDParams) WithUUID(uuid string) *GetNetworksUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get networks UUID params
func (o *GetNetworksUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworksUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
