package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// PostNetworksListReader is a Reader for the PostNetworksList structure.
type PostNetworksListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostNetworksListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostNetworksListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostNetworksListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostNetworksListOK creates a PostNetworksListOK with default headers values
func NewPostNetworksListOK() *PostNetworksListOK {
	return &PostNetworksListOK{}
}

/*PostNetworksListOK handles this case with default header values.

Successful operation
*/
type PostNetworksListOK struct {
	Payload *models.NetworkList
}

func (o *PostNetworksListOK) Error() string {
	return fmt.Sprintf("[POST /networks/list][%d] postNetworksListOK  %+v", 200, o.Payload)
}

func (o *PostNetworksListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostNetworksListDefault creates a PostNetworksListDefault with default headers values
func NewPostNetworksListDefault(code int) *PostNetworksListDefault {
	return &PostNetworksListDefault{
		_statusCode: code,
	}
}

/*PostNetworksListDefault handles this case with default header values.

Error
*/
type PostNetworksListDefault struct {
	_statusCode int

	Payload *models.NetworkStatus
}

// Code gets the status code for the post networks list default response
func (o *PostNetworksListDefault) Code() int {
	return o._statusCode
}

func (o *PostNetworksListDefault) Error() string {
	return fmt.Sprintf("[POST /networks/list][%d] PostNetworksList default  %+v", o._statusCode, o.Payload)
}

func (o *PostNetworksListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
