package docker_registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// DeleteDockerRegistriesUUIDReader is a Reader for the DeleteDockerRegistriesUUID structure.
type DeleteDockerRegistriesUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDockerRegistriesUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteDockerRegistriesUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteDockerRegistriesUUIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteDockerRegistriesUUIDOK creates a DeleteDockerRegistriesUUIDOK with default headers values
func NewDeleteDockerRegistriesUUIDOK() *DeleteDockerRegistriesUUIDOK {
	return &DeleteDockerRegistriesUUIDOK{}
}

/*DeleteDockerRegistriesUUIDOK handles this case with default header values.

Operation succeeded
*/
type DeleteDockerRegistriesUUIDOK struct {
}

func (o *DeleteDockerRegistriesUUIDOK) Error() string {
	return fmt.Sprintf("[DELETE /docker_registries/{uuid}][%d] deleteDockerRegistriesUuidOK ", 200)
}

func (o *DeleteDockerRegistriesUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDockerRegistriesUUIDDefault creates a DeleteDockerRegistriesUUIDDefault with default headers values
func NewDeleteDockerRegistriesUUIDDefault(code int) *DeleteDockerRegistriesUUIDDefault {
	return &DeleteDockerRegistriesUUIDDefault{
		_statusCode: code,
	}
}

/*DeleteDockerRegistriesUUIDDefault handles this case with default header values.

Failed to delete docker registry
*/
type DeleteDockerRegistriesUUIDDefault struct {
	_statusCode int

	Payload *models.DockerRegistryStatus
}

// Code gets the status code for the delete docker registries UUID default response
func (o *DeleteDockerRegistriesUUIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteDockerRegistriesUUIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /docker_registries/{uuid}][%d] DeleteDockerRegistriesUUID default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteDockerRegistriesUUIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DockerRegistryStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
