package docker_registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDockerRegistriesUUIDParams creates a new GetDockerRegistriesUUIDParams object
// with the default values initialized.
func NewGetDockerRegistriesUUIDParams() *GetDockerRegistriesUUIDParams {
	var ()
	return &GetDockerRegistriesUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDockerRegistriesUUIDParamsWithTimeout creates a new GetDockerRegistriesUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDockerRegistriesUUIDParamsWithTimeout(timeout time.Duration) *GetDockerRegistriesUUIDParams {
	var ()
	return &GetDockerRegistriesUUIDParams{

		timeout: timeout,
	}
}

// NewGetDockerRegistriesUUIDParamsWithContext creates a new GetDockerRegistriesUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDockerRegistriesUUIDParamsWithContext(ctx context.Context) *GetDockerRegistriesUUIDParams {
	var ()
	return &GetDockerRegistriesUUIDParams{

		Context: ctx,
	}
}

/*GetDockerRegistriesUUIDParams contains all the parameters to send to the API endpoint
for the get docker registries UUID operation typically these are written to a http.Request
*/
type GetDockerRegistriesUUIDParams struct {

	/*UUID
	  The UUID of the entity.

	*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get docker registries UUID params
func (o *GetDockerRegistriesUUIDParams) WithTimeout(timeout time.Duration) *GetDockerRegistriesUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get docker registries UUID params
func (o *GetDockerRegistriesUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get docker registries UUID params
func (o *GetDockerRegistriesUUIDParams) WithContext(ctx context.Context) *GetDockerRegistriesUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get docker registries UUID params
func (o *GetDockerRegistriesUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithUUID adds the uuid to the get docker registries UUID params
func (o *GetDockerRegistriesUUIDParams) WithUUID(uuid string) *GetDockerRegistriesUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get docker registries UUID params
func (o *GetDockerRegistriesUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetDockerRegistriesUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
