package docker_registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// NewPostDockerRegistriesUUIDSearchListParams creates a new PostDockerRegistriesUUIDSearchListParams object
// with the default values initialized.
func NewPostDockerRegistriesUUIDSearchListParams() *PostDockerRegistriesUUIDSearchListParams {
	var ()
	return &PostDockerRegistriesUUIDSearchListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDockerRegistriesUUIDSearchListParamsWithTimeout creates a new PostDockerRegistriesUUIDSearchListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDockerRegistriesUUIDSearchListParamsWithTimeout(timeout time.Duration) *PostDockerRegistriesUUIDSearchListParams {
	var ()
	return &PostDockerRegistriesUUIDSearchListParams{

		timeout: timeout,
	}
}

// NewPostDockerRegistriesUUIDSearchListParamsWithContext creates a new PostDockerRegistriesUUIDSearchListParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDockerRegistriesUUIDSearchListParamsWithContext(ctx context.Context) *PostDockerRegistriesUUIDSearchListParams {
	var ()
	return &PostDockerRegistriesUUIDSearchListParams{

		Context: ctx,
	}
}

/*PostDockerRegistriesUUIDSearchListParams contains all the parameters to send to the API endpoint
for the post docker registries UUID search list operation typically these are written to a http.Request
*/
type PostDockerRegistriesUUIDSearchListParams struct {

	/*Metadata*/
	Metadata *models.DockerRegistryImageSearch
	/*UUID
	  The UUID of the entity.

	*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the post docker registries UUID search list params
func (o *PostDockerRegistriesUUIDSearchListParams) WithTimeout(timeout time.Duration) *PostDockerRegistriesUUIDSearchListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post docker registries UUID search list params
func (o *PostDockerRegistriesUUIDSearchListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post docker registries UUID search list params
func (o *PostDockerRegistriesUUIDSearchListParams) WithContext(ctx context.Context) *PostDockerRegistriesUUIDSearchListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post docker registries UUID search list params
func (o *PostDockerRegistriesUUIDSearchListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithMetadata adds the metadata to the post docker registries UUID search list params
func (o *PostDockerRegistriesUUIDSearchListParams) WithMetadata(metadata *models.DockerRegistryImageSearch) *PostDockerRegistriesUUIDSearchListParams {
	o.SetMetadata(metadata)
	return o
}

// SetMetadata adds the metadata to the post docker registries UUID search list params
func (o *PostDockerRegistriesUUIDSearchListParams) SetMetadata(metadata *models.DockerRegistryImageSearch) {
	o.Metadata = metadata
}

// WithUUID adds the uuid to the post docker registries UUID search list params
func (o *PostDockerRegistriesUUIDSearchListParams) WithUUID(uuid string) *PostDockerRegistriesUUIDSearchListParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the post docker registries UUID search list params
func (o *PostDockerRegistriesUUIDSearchListParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *PostDockerRegistriesUUIDSearchListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Metadata == nil {
		o.Metadata = new(models.DockerRegistryImageSearch)
	}

	if err := r.SetBodyParam(o.Metadata); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
