package volume_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteVolumeGroupsUUIDParams creates a new DeleteVolumeGroupsUUIDParams object
// with the default values initialized.
func NewDeleteVolumeGroupsUUIDParams() *DeleteVolumeGroupsUUIDParams {
	var ()
	return &DeleteVolumeGroupsUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVolumeGroupsUUIDParamsWithTimeout creates a new DeleteVolumeGroupsUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteVolumeGroupsUUIDParamsWithTimeout(timeout time.Duration) *DeleteVolumeGroupsUUIDParams {
	var ()
	return &DeleteVolumeGroupsUUIDParams{

		timeout: timeout,
	}
}

// NewDeleteVolumeGroupsUUIDParamsWithContext creates a new DeleteVolumeGroupsUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteVolumeGroupsUUIDParamsWithContext(ctx context.Context) *DeleteVolumeGroupsUUIDParams {
	var ()
	return &DeleteVolumeGroupsUUIDParams{

		Context: ctx,
	}
}

/*DeleteVolumeGroupsUUIDParams contains all the parameters to send to the API endpoint
for the delete volume groups UUID operation typically these are written to a http.Request
*/
type DeleteVolumeGroupsUUIDParams struct {

	/*UUID
	  The UUID of the entity.

	*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the delete volume groups UUID params
func (o *DeleteVolumeGroupsUUIDParams) WithTimeout(timeout time.Duration) *DeleteVolumeGroupsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete volume groups UUID params
func (o *DeleteVolumeGroupsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete volume groups UUID params
func (o *DeleteVolumeGroupsUUIDParams) WithContext(ctx context.Context) *DeleteVolumeGroupsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete volume groups UUID params
func (o *DeleteVolumeGroupsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithUUID adds the uuid to the delete volume groups UUID params
func (o *DeleteVolumeGroupsUUIDParams) WithUUID(uuid string) *DeleteVolumeGroupsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete volume groups UUID params
func (o *DeleteVolumeGroupsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVolumeGroupsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
