package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPermissionsUUIDParams creates a new GetPermissionsUUIDParams object
// with the default values initialized.
func NewGetPermissionsUUIDParams() *GetPermissionsUUIDParams {
	var ()
	return &GetPermissionsUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPermissionsUUIDParamsWithTimeout creates a new GetPermissionsUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPermissionsUUIDParamsWithTimeout(timeout time.Duration) *GetPermissionsUUIDParams {
	var ()
	return &GetPermissionsUUIDParams{

		timeout: timeout,
	}
}

// NewGetPermissionsUUIDParamsWithContext creates a new GetPermissionsUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPermissionsUUIDParamsWithContext(ctx context.Context) *GetPermissionsUUIDParams {
	var ()
	return &GetPermissionsUUIDParams{

		Context: ctx,
	}
}

/*GetPermissionsUUIDParams contains all the parameters to send to the API endpoint
for the get permissions UUID operation typically these are written to a http.Request
*/
type GetPermissionsUUIDParams struct {

	/*UUID
	  ID of permission that needs to be fetched

	*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get permissions UUID params
func (o *GetPermissionsUUIDParams) WithTimeout(timeout time.Duration) *GetPermissionsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get permissions UUID params
func (o *GetPermissionsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get permissions UUID params
func (o *GetPermissionsUUIDParams) WithContext(ctx context.Context) *GetPermissionsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get permissions UUID params
func (o *GetPermissionsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithUUID adds the uuid to the get permissions UUID params
func (o *GetPermissionsUUIDParams) WithUUID(uuid string) *GetPermissionsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get permissions UUID params
func (o *GetPermissionsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetPermissionsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
