package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// DeleteHostsUUIDReader is a Reader for the DeleteHostsUUID structure.
type DeleteHostsUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteHostsUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteHostsUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteHostsUUIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteHostsUUIDOK creates a DeleteHostsUUIDOK with default headers values
func NewDeleteHostsUUIDOK() *DeleteHostsUUIDOK {
	return &DeleteHostsUUIDOK{}
}

/*DeleteHostsUUIDOK handles this case with default header values.

Success
*/
type DeleteHostsUUIDOK struct {
}

func (o *DeleteHostsUUIDOK) Error() string {
	return fmt.Sprintf("[DELETE /hosts/{uuid}][%d] deleteHostsUuidOK ", 200)
}

func (o *DeleteHostsUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteHostsUUIDDefault creates a DeleteHostsUUIDDefault with default headers values
func NewDeleteHostsUUIDDefault(code int) *DeleteHostsUUIDDefault {
	return &DeleteHostsUUIDDefault{
		_statusCode: code,
	}
}

/*DeleteHostsUUIDDefault handles this case with default header values.

Internal error
*/
type DeleteHostsUUIDDefault struct {
	_statusCode int

	Payload *models.HostStatus
}

// Code gets the status code for the delete hosts UUID default response
func (o *DeleteHostsUUIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteHostsUUIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /hosts/{uuid}][%d] DeleteHostsUUID default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteHostsUUIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HostStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
