package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetHostsUUIDParams creates a new GetHostsUUIDParams object
// with the default values initialized.
func NewGetHostsUUIDParams() *GetHostsUUIDParams {
	var ()
	return &GetHostsUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHostsUUIDParamsWithTimeout creates a new GetHostsUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHostsUUIDParamsWithTimeout(timeout time.Duration) *GetHostsUUIDParams {
	var ()
	return &GetHostsUUIDParams{

		timeout: timeout,
	}
}

// NewGetHostsUUIDParamsWithContext creates a new GetHostsUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHostsUUIDParamsWithContext(ctx context.Context) *GetHostsUUIDParams {
	var ()
	return &GetHostsUUIDParams{

		Context: ctx,
	}
}

/*GetHostsUUIDParams contains all the parameters to send to the API endpoint
for the get hosts UUID operation typically these are written to a http.Request
*/
type GetHostsUUIDParams struct {

	/*UUID
	  The UUID of the entity.

	*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get hosts UUID params
func (o *GetHostsUUIDParams) WithTimeout(timeout time.Duration) *GetHostsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get hosts UUID params
func (o *GetHostsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get hosts UUID params
func (o *GetHostsUUIDParams) WithContext(ctx context.Context) *GetHostsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get hosts UUID params
func (o *GetHostsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithUUID adds the uuid to the get hosts UUID params
func (o *GetHostsUUIDParams) WithUUID(uuid string) *GetHostsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get hosts UUID params
func (o *GetHostsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetHostsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
