package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// DeleteCategoriesNameValueReader is a Reader for the DeleteCategoriesNameValue structure.
type DeleteCategoriesNameValueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCategoriesNameValueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteCategoriesNameValueOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteCategoriesNameValueDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteCategoriesNameValueOK creates a DeleteCategoriesNameValueOK with default headers values
func NewDeleteCategoriesNameValueOK() *DeleteCategoriesNameValueOK {
	return &DeleteCategoriesNameValueOK{}
}

/*DeleteCategoriesNameValueOK handles this case with default header values.

Success
*/
type DeleteCategoriesNameValueOK struct {
}

func (o *DeleteCategoriesNameValueOK) Error() string {
	return fmt.Sprintf("[DELETE /categories/{name}/{value}][%d] deleteCategoriesNameValueOK ", 200)
}

func (o *DeleteCategoriesNameValueOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCategoriesNameValueDefault creates a DeleteCategoriesNameValueDefault with default headers values
func NewDeleteCategoriesNameValueDefault(code int) *DeleteCategoriesNameValueDefault {
	return &DeleteCategoriesNameValueDefault{
		_statusCode: code,
	}
}

/*DeleteCategoriesNameValueDefault handles this case with default header values.

Internal Error
*/
type DeleteCategoriesNameValueDefault struct {
	_statusCode int

	Payload *models.CategoryStatus
}

// Code gets the status code for the delete categories name value default response
func (o *DeleteCategoriesNameValueDefault) Code() int {
	return o._statusCode
}

func (o *DeleteCategoriesNameValueDefault) Error() string {
	return fmt.Sprintf("[DELETE /categories/{name}/{value}][%d] DeleteCategoriesNameValue default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteCategoriesNameValueDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CategoryStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
