package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCategoriesNameValueParams creates a new GetCategoriesNameValueParams object
// with the default values initialized.
func NewGetCategoriesNameValueParams() *GetCategoriesNameValueParams {
	var ()
	return &GetCategoriesNameValueParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCategoriesNameValueParamsWithTimeout creates a new GetCategoriesNameValueParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCategoriesNameValueParamsWithTimeout(timeout time.Duration) *GetCategoriesNameValueParams {
	var ()
	return &GetCategoriesNameValueParams{

		timeout: timeout,
	}
}

// NewGetCategoriesNameValueParamsWithContext creates a new GetCategoriesNameValueParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCategoriesNameValueParamsWithContext(ctx context.Context) *GetCategoriesNameValueParams {
	var ()
	return &GetCategoriesNameValueParams{

		Context: ctx,
	}
}

/*GetCategoriesNameValueParams contains all the parameters to send to the API endpoint
for the get categories name value operation typically these are written to a http.Request
*/
type GetCategoriesNameValueParams struct {

	/*Name*/
	Name string
	/*Value*/
	Value string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get categories name value params
func (o *GetCategoriesNameValueParams) WithTimeout(timeout time.Duration) *GetCategoriesNameValueParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get categories name value params
func (o *GetCategoriesNameValueParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get categories name value params
func (o *GetCategoriesNameValueParams) WithContext(ctx context.Context) *GetCategoriesNameValueParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get categories name value params
func (o *GetCategoriesNameValueParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithName adds the name to the get categories name value params
func (o *GetCategoriesNameValueParams) WithName(name string) *GetCategoriesNameValueParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get categories name value params
func (o *GetCategoriesNameValueParams) SetName(name string) {
	o.Name = name
}

// WithValue adds the value to the get categories name value params
func (o *GetCategoriesNameValueParams) WithValue(value string) *GetCategoriesNameValueParams {
	o.SetValue(value)
	return o
}

// SetValue adds the value to the get categories name value params
func (o *GetCategoriesNameValueParams) SetValue(value string) {
	o.Value = value
}

// WriteToRequest writes these params to a swagger request
func (o *GetCategoriesNameValueParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param value
	if err := r.SetPathParam("value", o.Value); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
