package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// PostCategoriesListReader is a Reader for the PostCategoriesList structure.
type PostCategoriesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCategoriesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostCategoriesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostCategoriesListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostCategoriesListOK creates a PostCategoriesListOK with default headers values
func NewPostCategoriesListOK() *PostCategoriesListOK {
	return &PostCategoriesListOK{}
}

/*PostCategoriesListOK handles this case with default header values.

Success
*/
type PostCategoriesListOK struct {
	Payload *models.CategoryListResponse
}

func (o *PostCategoriesListOK) Error() string {
	return fmt.Sprintf("[POST /categories/list][%d] postCategoriesListOK  %+v", 200, o.Payload)
}

func (o *PostCategoriesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CategoryListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCategoriesListDefault creates a PostCategoriesListDefault with default headers values
func NewPostCategoriesListDefault(code int) *PostCategoriesListDefault {
	return &PostCategoriesListDefault{
		_statusCode: code,
	}
}

/*PostCategoriesListDefault handles this case with default header values.

Error
*/
type PostCategoriesListDefault struct {
	_statusCode int

	Payload *models.CategoryStatus
}

// Code gets the status code for the post categories list default response
func (o *PostCategoriesListDefault) Code() int {
	return o._statusCode
}

func (o *PostCategoriesListDefault) Error() string {
	return fmt.Sprintf("[POST /categories/list][%d] PostCategoriesList default  %+v", o._statusCode, o.Payload)
}

func (o *PostCategoriesListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CategoryStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
