package vm_snapshot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetVMSnapshotsUUIDParams creates a new GetVMSnapshotsUUIDParams object
// with the default values initialized.
func NewGetVMSnapshotsUUIDParams() *GetVMSnapshotsUUIDParams {
	var ()
	return &GetVMSnapshotsUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVMSnapshotsUUIDParamsWithTimeout creates a new GetVMSnapshotsUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVMSnapshotsUUIDParamsWithTimeout(timeout time.Duration) *GetVMSnapshotsUUIDParams {
	var ()
	return &GetVMSnapshotsUUIDParams{

		timeout: timeout,
	}
}

// NewGetVMSnapshotsUUIDParamsWithContext creates a new GetVMSnapshotsUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVMSnapshotsUUIDParamsWithContext(ctx context.Context) *GetVMSnapshotsUUIDParams {
	var ()
	return &GetVMSnapshotsUUIDParams{

		Context: ctx,
	}
}

/*GetVMSnapshotsUUIDParams contains all the parameters to send to the API endpoint
for the get VM snapshots UUID operation typically these are written to a http.Request
*/
type GetVMSnapshotsUUIDParams struct {

	/*UUID*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get VM snapshots UUID params
func (o *GetVMSnapshotsUUIDParams) WithTimeout(timeout time.Duration) *GetVMSnapshotsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get VM snapshots UUID params
func (o *GetVMSnapshotsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get VM snapshots UUID params
func (o *GetVMSnapshotsUUIDParams) WithContext(ctx context.Context) *GetVMSnapshotsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get VM snapshots UUID params
func (o *GetVMSnapshotsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithUUID adds the uuid to the get VM snapshots UUID params
func (o *GetVMSnapshotsUUIDParams) WithUUID(uuid string) *GetVMSnapshotsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get VM snapshots UUID params
func (o *GetVMSnapshotsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetVMSnapshotsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
