package vm_snapshot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// NewPostVMSnapshotsListParams creates a new PostVMSnapshotsListParams object
// with the default values initialized.
func NewPostVMSnapshotsListParams() *PostVMSnapshotsListParams {
	var ()
	return &PostVMSnapshotsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostVMSnapshotsListParamsWithTimeout creates a new PostVMSnapshotsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostVMSnapshotsListParamsWithTimeout(timeout time.Duration) *PostVMSnapshotsListParams {
	var ()
	return &PostVMSnapshotsListParams{

		timeout: timeout,
	}
}

// NewPostVMSnapshotsListParamsWithContext creates a new PostVMSnapshotsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostVMSnapshotsListParamsWithContext(ctx context.Context) *PostVMSnapshotsListParams {
	var ()
	return &PostVMSnapshotsListParams{

		Context: ctx,
	}
}

/*PostVMSnapshotsListParams contains all the parameters to send to the API endpoint
for the post VM snapshots list operation typically these are written to a http.Request
*/
type PostVMSnapshotsListParams struct {

	/*GetEntitiesRequest*/
	GetEntitiesRequest *models.VMSnapshotListMetadata

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the post VM snapshots list params
func (o *PostVMSnapshotsListParams) WithTimeout(timeout time.Duration) *PostVMSnapshotsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post VM snapshots list params
func (o *PostVMSnapshotsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post VM snapshots list params
func (o *PostVMSnapshotsListParams) WithContext(ctx context.Context) *PostVMSnapshotsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post VM snapshots list params
func (o *PostVMSnapshotsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithGetEntitiesRequest adds the getEntitiesRequest to the post VM snapshots list params
func (o *PostVMSnapshotsListParams) WithGetEntitiesRequest(getEntitiesRequest *models.VMSnapshotListMetadata) *PostVMSnapshotsListParams {
	o.SetGetEntitiesRequest(getEntitiesRequest)
	return o
}

// SetGetEntitiesRequest adds the getEntitiesRequest to the post VM snapshots list params
func (o *PostVMSnapshotsListParams) SetGetEntitiesRequest(getEntitiesRequest *models.VMSnapshotListMetadata) {
	o.GetEntitiesRequest = getEntitiesRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostVMSnapshotsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.GetEntitiesRequest == nil {
		o.GetEntitiesRequest = new(models.VMSnapshotListMetadata)
	}

	if err := r.SetBodyParam(o.GetEntitiesRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
