package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteJobsUUIDParams creates a new DeleteJobsUUIDParams object
// with the default values initialized.
func NewDeleteJobsUUIDParams() *DeleteJobsUUIDParams {
	var ()
	return &DeleteJobsUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteJobsUUIDParamsWithTimeout creates a new DeleteJobsUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteJobsUUIDParamsWithTimeout(timeout time.Duration) *DeleteJobsUUIDParams {
	var ()
	return &DeleteJobsUUIDParams{

		timeout: timeout,
	}
}

// NewDeleteJobsUUIDParamsWithContext creates a new DeleteJobsUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteJobsUUIDParamsWithContext(ctx context.Context) *DeleteJobsUUIDParams {
	var ()
	return &DeleteJobsUUIDParams{

		Context: ctx,
	}
}

/*DeleteJobsUUIDParams contains all the parameters to send to the API endpoint
for the delete jobs UUID operation typically these are written to a http.Request
*/
type DeleteJobsUUIDParams struct {

	/*UUID
	  Uuid of the job to be deleted

	*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the delete jobs UUID params
func (o *DeleteJobsUUIDParams) WithTimeout(timeout time.Duration) *DeleteJobsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete jobs UUID params
func (o *DeleteJobsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete jobs UUID params
func (o *DeleteJobsUUIDParams) WithContext(ctx context.Context) *DeleteJobsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete jobs UUID params
func (o *DeleteJobsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithUUID adds the uuid to the delete jobs UUID params
func (o *DeleteJobsUUIDParams) WithUUID(uuid string) *DeleteJobsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete jobs UUID params
func (o *DeleteJobsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteJobsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
