package oauth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteOauthTokenUnregisterClientIDParams creates a new DeleteOauthTokenUnregisterClientIDParams object
// with the default values initialized.
func NewDeleteOauthTokenUnregisterClientIDParams() *DeleteOauthTokenUnregisterClientIDParams {
	var ()
	return &DeleteOauthTokenUnregisterClientIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOauthTokenUnregisterClientIDParamsWithTimeout creates a new DeleteOauthTokenUnregisterClientIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteOauthTokenUnregisterClientIDParamsWithTimeout(timeout time.Duration) *DeleteOauthTokenUnregisterClientIDParams {
	var ()
	return &DeleteOauthTokenUnregisterClientIDParams{

		timeout: timeout,
	}
}

// NewDeleteOauthTokenUnregisterClientIDParamsWithContext creates a new DeleteOauthTokenUnregisterClientIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteOauthTokenUnregisterClientIDParamsWithContext(ctx context.Context) *DeleteOauthTokenUnregisterClientIDParams {
	var ()
	return &DeleteOauthTokenUnregisterClientIDParams{

		Context: ctx,
	}
}

/*DeleteOauthTokenUnregisterClientIDParams contains all the parameters to send to the API endpoint
for the delete oauth token unregister client ID operation typically these are written to a http.Request
*/
type DeleteOauthTokenUnregisterClientIDParams struct {

	/*ClientID*/
	ClientID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the delete oauth token unregister client ID params
func (o *DeleteOauthTokenUnregisterClientIDParams) WithTimeout(timeout time.Duration) *DeleteOauthTokenUnregisterClientIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete oauth token unregister client ID params
func (o *DeleteOauthTokenUnregisterClientIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete oauth token unregister client ID params
func (o *DeleteOauthTokenUnregisterClientIDParams) WithContext(ctx context.Context) *DeleteOauthTokenUnregisterClientIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete oauth token unregister client ID params
func (o *DeleteOauthTokenUnregisterClientIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithClientID adds the clientID to the delete oauth token unregister client ID params
func (o *DeleteOauthTokenUnregisterClientIDParams) WithClientID(clientID string) *DeleteOauthTokenUnregisterClientIDParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the delete oauth token unregister client ID params
func (o *DeleteOauthTokenUnregisterClientIDParams) SetClientID(clientID string) {
	o.ClientID = clientID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOauthTokenUnregisterClientIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param client_id
	if err := r.SetPathParam("client_id", o.ClientID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
