package oauth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// NewPostOauthClientParams creates a new PostOauthClientParams object
// with the default values initialized.
func NewPostOauthClientParams() *PostOauthClientParams {
	var ()
	return &PostOauthClientParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostOauthClientParamsWithTimeout creates a new PostOauthClientParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostOauthClientParamsWithTimeout(timeout time.Duration) *PostOauthClientParams {
	var ()
	return &PostOauthClientParams{

		timeout: timeout,
	}
}

// NewPostOauthClientParamsWithContext creates a new PostOauthClientParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostOauthClientParamsWithContext(ctx context.Context) *PostOauthClientParams {
	var ()
	return &PostOauthClientParams{

		Context: ctx,
	}
}

/*PostOauthClientParams contains all the parameters to send to the API endpoint
for the post oauth client operation typically these are written to a http.Request
*/
type PostOauthClientParams struct {

	/*OauthClient
	  Oauth client details

	*/
	OauthClient *models.OauthClientInput

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the post oauth client params
func (o *PostOauthClientParams) WithTimeout(timeout time.Duration) *PostOauthClientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post oauth client params
func (o *PostOauthClientParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post oauth client params
func (o *PostOauthClientParams) WithContext(ctx context.Context) *PostOauthClientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post oauth client params
func (o *PostOauthClientParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithOauthClient adds the oauthClient to the post oauth client params
func (o *PostOauthClientParams) WithOauthClient(oauthClient *models.OauthClientInput) *PostOauthClientParams {
	o.SetOauthClient(oauthClient)
	return o
}

// SetOauthClient adds the oauthClient to the post oauth client params
func (o *PostOauthClientParams) SetOauthClient(oauthClient *models.OauthClientInput) {
	o.OauthClient = oauthClient
}

// WriteToRequest writes these params to a swagger request
func (o *PostOauthClientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.OauthClient == nil {
		o.OauthClient = new(models.OauthClientInput)
	}

	if err := r.SetBodyParam(o.OauthClient); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
