package oauth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// PostOauthClientListReader is a Reader for the PostOauthClientList structure.
type PostOauthClientListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostOauthClientListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostOauthClientListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostOauthClientListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostOauthClientListOK creates a PostOauthClientListOK with default headers values
func NewPostOauthClientListOK() *PostOauthClientListOK {
	return &PostOauthClientListOK{}
}

/*PostOauthClientListOK handles this case with default header values.

Retrieved all oauth clients
*/
type PostOauthClientListOK struct {
	Payload *models.OauthClientList
}

func (o *PostOauthClientListOK) Error() string {
	return fmt.Sprintf("[POST /oauth/client/list][%d] postOauthClientListOK  %+v", 200, o.Payload)
}

func (o *PostOauthClientListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OauthClientList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOauthClientListDefault creates a PostOauthClientListDefault with default headers values
func NewPostOauthClientListDefault(code int) *PostOauthClientListDefault {
	return &PostOauthClientListDefault{
		_statusCode: code,
	}
}

/*PostOauthClientListDefault handles this case with default header values.

Failed to retrieve all projects
*/
type PostOauthClientListDefault struct {
	_statusCode int

	Payload *models.OauthClientStatus
}

// Code gets the status code for the post oauth client list default response
func (o *PostOauthClientListDefault) Code() int {
	return o._statusCode
}

func (o *PostOauthClientListDefault) Error() string {
	return fmt.Sprintf("[POST /oauth/client/list][%d] PostOauthClientList default  %+v", o._statusCode, o.Payload)
}

func (o *PostOauthClientListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OauthClientStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
