package oauth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// PostOauthClientReader is a Reader for the PostOauthClient structure.
type PostOauthClientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostOauthClientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostOauthClientOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostOauthClientDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostOauthClientOK creates a PostOauthClientOK with default headers values
func NewPostOauthClientOK() *PostOauthClientOK {
	return &PostOauthClientOK{}
}

/*PostOauthClientOK handles this case with default header values.

Successful operation
*/
type PostOauthClientOK struct {
	Payload *models.OauthClientResponse
}

func (o *PostOauthClientOK) Error() string {
	return fmt.Sprintf("[POST /oauth/client][%d] postOauthClientOK  %+v", 200, o.Payload)
}

func (o *PostOauthClientOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OauthClientResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOauthClientDefault creates a PostOauthClientDefault with default headers values
func NewPostOauthClientDefault(code int) *PostOauthClientDefault {
	return &PostOauthClientDefault{
		_statusCode: code,
	}
}

/*PostOauthClientDefault handles this case with default header values.

Error
*/
type PostOauthClientDefault struct {
	_statusCode int

	Payload *models.OauthClientStatus
}

// Code gets the status code for the post oauth client default response
func (o *PostOauthClientDefault) Code() int {
	return o._statusCode
}

func (o *PostOauthClientDefault) Error() string {
	return fmt.Sprintf("[POST /oauth/client][%d] PostOauthClient default  %+v", o._statusCode, o.Payload)
}

func (o *PostOauthClientDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OauthClientStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
