package oauth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// NewPutOauthClientClientIDParams creates a new PutOauthClientClientIDParams object
// with the default values initialized.
func NewPutOauthClientClientIDParams() *PutOauthClientClientIDParams {
	var ()
	return &PutOauthClientClientIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutOauthClientClientIDParamsWithTimeout creates a new PutOauthClientClientIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutOauthClientClientIDParamsWithTimeout(timeout time.Duration) *PutOauthClientClientIDParams {
	var ()
	return &PutOauthClientClientIDParams{

		timeout: timeout,
	}
}

// NewPutOauthClientClientIDParamsWithContext creates a new PutOauthClientClientIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutOauthClientClientIDParamsWithContext(ctx context.Context) *PutOauthClientClientIDParams {
	var ()
	return &PutOauthClientClientIDParams{

		Context: ctx,
	}
}

/*PutOauthClientClientIDParams contains all the parameters to send to the API endpoint
for the put oauth client client ID operation typically these are written to a http.Request
*/
type PutOauthClientClientIDParams struct {

	/*ClientID*/
	ClientID string
	/*OauthClient
	  Oauth client details

	*/
	OauthClient *models.OauthClientInput

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the put oauth client client ID params
func (o *PutOauthClientClientIDParams) WithTimeout(timeout time.Duration) *PutOauthClientClientIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put oauth client client ID params
func (o *PutOauthClientClientIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put oauth client client ID params
func (o *PutOauthClientClientIDParams) WithContext(ctx context.Context) *PutOauthClientClientIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put oauth client client ID params
func (o *PutOauthClientClientIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithClientID adds the clientID to the put oauth client client ID params
func (o *PutOauthClientClientIDParams) WithClientID(clientID string) *PutOauthClientClientIDParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the put oauth client client ID params
func (o *PutOauthClientClientIDParams) SetClientID(clientID string) {
	o.ClientID = clientID
}

// WithOauthClient adds the oauthClient to the put oauth client client ID params
func (o *PutOauthClientClientIDParams) WithOauthClient(oauthClient *models.OauthClientInput) *PutOauthClientClientIDParams {
	o.SetOauthClient(oauthClient)
	return o
}

// SetOauthClient adds the oauthClient to the put oauth client client ID params
func (o *PutOauthClientClientIDParams) SetOauthClient(oauthClient *models.OauthClientInput) {
	o.OauthClient = oauthClient
}

// WriteToRequest writes these params to a swagger request
func (o *PutOauthClientClientIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param client_id
	if err := r.SetPathParam("client_id", o.ClientID); err != nil {
		return err
	}

	if o.OauthClient == nil {
		o.OauthClient = new(models.OauthClientInput)
	}

	if err := r.SetBodyParam(o.OauthClient); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
