package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// NewPutWebhooksUUIDParams creates a new PutWebhooksUUIDParams object
// with the default values initialized.
func NewPutWebhooksUUIDParams() *PutWebhooksUUIDParams {
	var ()
	return &PutWebhooksUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutWebhooksUUIDParamsWithTimeout creates a new PutWebhooksUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutWebhooksUUIDParamsWithTimeout(timeout time.Duration) *PutWebhooksUUIDParams {
	var ()
	return &PutWebhooksUUIDParams{

		timeout: timeout,
	}
}

// NewPutWebhooksUUIDParamsWithContext creates a new PutWebhooksUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutWebhooksUUIDParamsWithContext(ctx context.Context) *PutWebhooksUUIDParams {
	var ()
	return &PutWebhooksUUIDParams{

		Context: ctx,
	}
}

/*PutWebhooksUUIDParams contains all the parameters to send to the API endpoint
for the put webhooks UUID operation typically these are written to a http.Request
*/
type PutWebhooksUUIDParams struct {

	/*Body*/
	Body *models.WebhookIntentInput
	/*UUID*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the put webhooks UUID params
func (o *PutWebhooksUUIDParams) WithTimeout(timeout time.Duration) *PutWebhooksUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put webhooks UUID params
func (o *PutWebhooksUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put webhooks UUID params
func (o *PutWebhooksUUIDParams) WithContext(ctx context.Context) *PutWebhooksUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put webhooks UUID params
func (o *PutWebhooksUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the put webhooks UUID params
func (o *PutWebhooksUUIDParams) WithBody(body *models.WebhookIntentInput) *PutWebhooksUUIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put webhooks UUID params
func (o *PutWebhooksUUIDParams) SetBody(body *models.WebhookIntentInput) {
	o.Body = body
}

// WithUUID adds the uuid to the put webhooks UUID params
func (o *PutWebhooksUUIDParams) WithUUID(uuid string) *PutWebhooksUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the put webhooks UUID params
func (o *PutWebhooksUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *PutWebhooksUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.WebhookIntentInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
