package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/intent_api/models"
)

// NewPostVmsListParams creates a new PostVmsListParams object
// with the default values initialized.
func NewPostVmsListParams() *PostVmsListParams {
	var ()
	return &PostVmsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostVmsListParamsWithTimeout creates a new PostVmsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostVmsListParamsWithTimeout(timeout time.Duration) *PostVmsListParams {
	var ()
	return &PostVmsListParams{

		timeout: timeout,
	}
}

// NewPostVmsListParamsWithContext creates a new PostVmsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostVmsListParamsWithContext(ctx context.Context) *PostVmsListParams {
	var ()
	return &PostVmsListParams{

		Context: ctx,
	}
}

/*PostVmsListParams contains all the parameters to send to the API endpoint
for the post vms list operation typically these are written to a http.Request
*/
type PostVmsListParams struct {

	/*GetEntitiesRequest*/
	GetEntitiesRequest *models.VMListMetadata

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the post vms list params
func (o *PostVmsListParams) WithTimeout(timeout time.Duration) *PostVmsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post vms list params
func (o *PostVmsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post vms list params
func (o *PostVmsListParams) WithContext(ctx context.Context) *PostVmsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post vms list params
func (o *PostVmsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithGetEntitiesRequest adds the getEntitiesRequest to the post vms list params
func (o *PostVmsListParams) WithGetEntitiesRequest(getEntitiesRequest *models.VMListMetadata) *PostVmsListParams {
	o.SetGetEntitiesRequest(getEntitiesRequest)
	return o
}

// SetGetEntitiesRequest adds the getEntitiesRequest to the post vms list params
func (o *PostVmsListParams) SetGetEntitiesRequest(getEntitiesRequest *models.VMListMetadata) {
	o.GetEntitiesRequest = getEntitiesRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostVmsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.GetEntitiesRequest == nil {
		o.GetEntitiesRequest = new(models.VMListMetadata)
	}

	if err := r.SetBodyParam(o.GetEntitiesRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
