package vm_backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetVMBackupsUUIDParams creates a new GetVMBackupsUUIDParams object
// with the default values initialized.
func NewGetVMBackupsUUIDParams() *GetVMBackupsUUIDParams {
	var ()
	return &GetVMBackupsUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVMBackupsUUIDParamsWithTimeout creates a new GetVMBackupsUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVMBackupsUUIDParamsWithTimeout(timeout time.Duration) *GetVMBackupsUUIDParams {
	var ()
	return &GetVMBackupsUUIDParams{

		timeout: timeout,
	}
}

// NewGetVMBackupsUUIDParamsWithContext creates a new GetVMBackupsUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVMBackupsUUIDParamsWithContext(ctx context.Context) *GetVMBackupsUUIDParams {
	var ()
	return &GetVMBackupsUUIDParams{

		Context: ctx,
	}
}

/*GetVMBackupsUUIDParams contains all the parameters to send to the API endpoint
for the get VM backups UUID operation typically these are written to a http.Request
*/
type GetVMBackupsUUIDParams struct {

	/*UUID*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get VM backups UUID params
func (o *GetVMBackupsUUIDParams) WithTimeout(timeout time.Duration) *GetVMBackupsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get VM backups UUID params
func (o *GetVMBackupsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get VM backups UUID params
func (o *GetVMBackupsUUIDParams) WithContext(ctx context.Context) *GetVMBackupsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get VM backups UUID params
func (o *GetVMBackupsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithUUID adds the uuid to the get VM backups UUID params
func (o *GetVMBackupsUUIDParams) WithUUID(uuid string) *GetVMBackupsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get VM backups UUID params
func (o *GetVMBackupsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetVMBackupsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
