package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codervinod/intent_api/models"
)

// NewPutProjectsUUIDParams creates a new PutProjectsUUIDParams object
// with the default values initialized.
func NewPutProjectsUUIDParams() *PutProjectsUUIDParams {
	var ()
	return &PutProjectsUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutProjectsUUIDParamsWithTimeout creates a new PutProjectsUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutProjectsUUIDParamsWithTimeout(timeout time.Duration) *PutProjectsUUIDParams {
	var ()
	return &PutProjectsUUIDParams{

		timeout: timeout,
	}
}

// NewPutProjectsUUIDParamsWithContext creates a new PutProjectsUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutProjectsUUIDParamsWithContext(ctx context.Context) *PutProjectsUUIDParams {
	var ()
	return &PutProjectsUUIDParams{

		Context: ctx,
	}
}

/*PutProjectsUUIDParams contains all the parameters to send to the API endpoint
for the put projects UUID operation typically these are written to a http.Request
*/
type PutProjectsUUIDParams struct {

	/*Body
	  Project object

	*/
	Body *models.Project
	/*UUID
	  The UUID of the entity.

	*/
	UUID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the put projects UUID params
func (o *PutProjectsUUIDParams) WithTimeout(timeout time.Duration) *PutProjectsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put projects UUID params
func (o *PutProjectsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put projects UUID params
func (o *PutProjectsUUIDParams) WithContext(ctx context.Context) *PutProjectsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put projects UUID params
func (o *PutProjectsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the put projects UUID params
func (o *PutProjectsUUIDParams) WithBody(body *models.Project) *PutProjectsUUIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put projects UUID params
func (o *PutProjectsUUIDParams) SetBody(body *models.Project) {
	o.Body = body
}

// WithUUID adds the uuid to the put projects UUID params
func (o *PutProjectsUUIDParams) WithUUID(uuid string) *PutProjectsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the put projects UUID params
func (o *PutProjectsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *PutProjectsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.Project)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
