package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// ContainerBasicOptions Container minimum options definition
//
// Container params
// swagger:model container_basic_options
type ContainerBasicOptions struct {

	// Command to be executed for the container
	Command string `json:"command,omitempty"`

	// Number of cpus
	// Minimum: 1
	CPUShares int32 `json:"cpu_shares,omitempty"`

	// List of environment variables.
	Environments map[string]string `json:"environments,omitempty"`

	// Memory in MBs
	MemoryMb int32 `json:"memory_mb,omitempty"`

	// List of port mappings
	PortMappingReferenceList map[string]string `json:"port_mapping_reference_list,omitempty"`

	// Name of container provider
	ProviderName string `json:"provider_name,omitempty"`

	// Container restart policy
	RestartPolicy string `json:"restart_policy,omitempty"`

	// Map of Volume Group name to mount path
	VolumeMountMap map[string]string `json:"volume_mount_map,omitempty"`
}

// Validate validates this container basic options
func (m *ContainerBasicOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCPUShares(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateEnvironments(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePortMappingReferenceList(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateProviderName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateVolumeMountMap(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContainerBasicOptions) validateCPUShares(formats strfmt.Registry) error {

	if swag.IsZero(m.CPUShares) { // not required
		return nil
	}

	if err := validate.MinimumInt("cpu_shares", "body", int64(m.CPUShares), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *ContainerBasicOptions) validateEnvironments(formats strfmt.Registry) error {

	if swag.IsZero(m.Environments) { // not required
		return nil
	}

	if err := validate.Required("environments", "body", m.Environments); err != nil {
		return err
	}

	return nil
}

func (m *ContainerBasicOptions) validatePortMappingReferenceList(formats strfmt.Registry) error {

	if swag.IsZero(m.PortMappingReferenceList) { // not required
		return nil
	}

	if err := validate.Required("port_mapping_reference_list", "body", m.PortMappingReferenceList); err != nil {
		return err
	}

	return nil
}

var containerBasicOptionsTypeProviderNamePropEnum []interface{}

const (
	containerBasicOptionsProviderNameDOCKER string = "DOCKER"
)

// prop value enum
func (m *ContainerBasicOptions) validateProviderNameEnum(path, location string, value string) error {
	if containerBasicOptionsTypeProviderNamePropEnum == nil {
		var res []string
		if err := json.Unmarshal([]byte(`["DOCKER"]`), &res); err != nil {
			return err
		}
		for _, v := range res {
			containerBasicOptionsTypeProviderNamePropEnum = append(containerBasicOptionsTypeProviderNamePropEnum, v)
		}
	}
	if err := validate.Enum(path, location, value, containerBasicOptionsTypeProviderNamePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ContainerBasicOptions) validateProviderName(formats strfmt.Registry) error {

	if swag.IsZero(m.ProviderName) { // not required
		return nil
	}

	// value enum
	if err := m.validateProviderNameEnum("provider_name", "body", m.ProviderName); err != nil {
		return err
	}

	return nil
}

func (m *ContainerBasicOptions) validateVolumeMountMap(formats strfmt.Registry) error {

	if swag.IsZero(m.VolumeMountMap) { // not required
		return nil
	}

	if err := validate.Required("volume_mount_map", "body", m.VolumeMountMap); err != nil {
		return err
	}

	return nil
}
