package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// DockerRegistryResources Docker Registry Resources
//
// Docker registry resources
// swagger:model docker_registry_resources
type DockerRegistryResources struct {

	// Cerfiticate required for the private docker registry
	Certificate string `json:"certificate,omitempty"`

	// Flag to indicate whether the docker registry is enabled or not
	//
	Enabled bool `json:"enabled,omitempty"`

	// Password of the user for the docker registry
	Password string `json:"password,omitempty"`

	// Flag to indicate whether the docker registry is a system default
	//
	// Read Only: true
	SystemDefault *bool `json:"system_default,omitempty"`

	// URL of the docker registry
	URL string `json:"url,omitempty"`

	// User name of the docker registry
	Username string `json:"username,omitempty"`
}

// Validate validates this docker registry resources
func (m *DockerRegistryResources) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
