package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DockerRegistryReference Reference to a docker_registry
//
// The reference to a docker_registry
// swagger:model docker_registry_reference
type DockerRegistryReference struct {

	// The kind name
	// Required: true
	// Read Only: true
	Kind string `json:"kind"`

	// name
	// Max Length: 140
	Name string `json:"name,omitempty"`

	// uuid
	// Pattern: \A[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}\Z
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this docker registry reference
func (m *DockerRegistryReference) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKind(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateUUID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var dockerRegistryReferenceTypeKindPropEnum []interface{}

const (
	dockerRegistryReferenceKindDockerRegistry string = "docker_registry"
)

// prop value enum
func (m *DockerRegistryReference) validateKindEnum(path, location string, value string) error {
	if dockerRegistryReferenceTypeKindPropEnum == nil {
		var res []string
		if err := json.Unmarshal([]byte(`["docker_registry"]`), &res); err != nil {
			return err
		}
		for _, v := range res {
			dockerRegistryReferenceTypeKindPropEnum = append(dockerRegistryReferenceTypeKindPropEnum, v)
		}
	}
	if err := validate.Enum(path, location, value, dockerRegistryReferenceTypeKindPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *DockerRegistryReference) validateKind(formats strfmt.Registry) error {

	if err := validate.RequiredString("kind", "body", string(m.Kind)); err != nil {
		return err
	}

	// value enum
	if err := m.validateKindEnum("kind", "body", m.Kind); err != nil {
		return err
	}

	return nil
}

func (m *DockerRegistryReference) validateName(formats strfmt.Registry) error {

	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.MaxLength("name", "body", string(m.Name), 140); err != nil {
		return err
	}

	return nil
}

func (m *DockerRegistryReference) validateUUID(formats strfmt.Registry) error {

	if swag.IsZero(m.UUID) { // not required
		return nil
	}

	if err := validate.Pattern("uuid", "body", string(m.UUID), `\A[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}\Z`); err != nil {
		return err
	}

	return nil
}
