package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// GroupsSortOrder Entities Request Sort Order
//
// Sort order for entities and entity groups
// swagger:model groups_sort_order
type GroupsSortOrder string

const (
	GroupsSortOrderASCENDING  GroupsSortOrder = "ASCENDING"
	GroupsSortOrderDESCENDING GroupsSortOrder = "DESCENDING"
)

// for schema
var groupsSortOrderEnum []interface{}

func (m GroupsSortOrder) validateGroupsSortOrderEnum(path, location string, value GroupsSortOrder) error {
	if groupsSortOrderEnum == nil {
		var res []GroupsSortOrder
		if err := json.Unmarshal([]byte(`["ASCENDING","DESCENDING"]`), &res); err != nil {
			return err
		}
		for _, v := range res {
			groupsSortOrderEnum = append(groupsSortOrderEnum, v)
		}
	}
	if err := validate.Enum(path, location, value, groupsSortOrderEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this groups sort order
func (m GroupsSortOrder) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateGroupsSortOrderEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
