package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// IdempotenceIdentifiersInput Idemopotence object
//
// Resources for the idempotence identifier kind
// swagger:model idempotence_identifiers_input
type IdempotenceIdentifiersInput struct {

	// Client identifier string
	// Required: true
	ClientIdentifier *string `json:"client_identifier"`

	// Number of idempotence identifier uuid
	// Required: true
	Count *int64 `json:"count"`
}

// Validate validates this idempotence identifiers input
func (m *IdempotenceIdentifiersInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientIdentifier(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateCount(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IdempotenceIdentifiersInput) validateClientIdentifier(formats strfmt.Registry) error {

	if err := validate.Required("client_identifier", "body", m.ClientIdentifier); err != nil {
		return err
	}

	return nil
}

func (m *IdempotenceIdentifiersInput) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("count", "body", m.Count); err != nil {
		return err
	}

	return nil
}
