package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// OauthClientInput Oauth client
//
// Oauth client information
// swagger:model oauth_client_input
type OauthClientInput struct {

	// client description of the Oauth Client
	// Required: true
	// Max Length: 1000
	ClientDescription *string `json:"client_description"`

	// client name of the Oauth Client
	// Required: true
	// Max Length: 140
	ClientName *string `json:"client_name"`

	// default scopes
	// Required: true
	DefaultScopes []string `json:"default_scopes"`

	// redirect uris
	// Required: true
	RedirectUris []string `json:"redirect_uris"`
}

// Validate validates this oauth client input
func (m *OauthClientInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientDescription(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateClientName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDefaultScopes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateRedirectUris(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OauthClientInput) validateClientDescription(formats strfmt.Registry) error {

	if err := validate.Required("client_description", "body", m.ClientDescription); err != nil {
		return err
	}

	if err := validate.MaxLength("client_description", "body", string(*m.ClientDescription), 1000); err != nil {
		return err
	}

	return nil
}

func (m *OauthClientInput) validateClientName(formats strfmt.Registry) error {

	if err := validate.Required("client_name", "body", m.ClientName); err != nil {
		return err
	}

	if err := validate.MaxLength("client_name", "body", string(*m.ClientName), 140); err != nil {
		return err
	}

	return nil
}

func (m *OauthClientInput) validateDefaultScopes(formats strfmt.Registry) error {

	if err := validate.Required("default_scopes", "body", m.DefaultScopes); err != nil {
		return err
	}

	return nil
}

func (m *OauthClientInput) validateRedirectUris(formats strfmt.Registry) error {

	if err := validate.Required("redirect_uris", "body", m.RedirectUris); err != nil {
		return err
	}

	return nil
}
