package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// SoftwareType Software type
//
// Software type
// swagger:model software_type
type SoftwareType struct {

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this software type
func (m *SoftwareType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var softwareTypeTypeTypePropEnum []interface{}

const (
	softwareTypeTypeNOS string = "NOS"
)

// prop value enum
func (m *SoftwareType) validateTypeEnum(path, location string, value string) error {
	if softwareTypeTypeTypePropEnum == nil {
		var res []string
		if err := json.Unmarshal([]byte(`["NOS"]`), &res); err != nil {
			return err
		}
		for _, v := range res {
			softwareTypeTypeTypePropEnum = append(softwareTypeTypeTypePropEnum, v)
		}
	}
	if err := validate.Enum(path, location, value, softwareTypeTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *SoftwareType) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}
