package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// Versions Versions
//
// Supported API Versions
// swagger:model versions
type Versions struct {

	// The major number of the API
	// Required: true
	MajorVersion *int64 `json:"major_version"`

	// The minor number of the API
	// Required: true
	MinorVersion *int64 `json:"minor_version"`
}

// Validate validates this versions
func (m *Versions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMajorVersion(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateMinorVersion(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Versions) validateMajorVersion(formats strfmt.Registry) error {

	if err := validate.Required("major_version", "body", m.MajorVersion); err != nil {
		return err
	}

	return nil
}

func (m *Versions) validateMinorVersion(formats strfmt.Registry) error {

	if err := validate.Required("minor_version", "body", m.MinorVersion); err != nil {
		return err
	}

	return nil
}
